### ISSUE TITLE
Head color can't be changed via shadowing

### ISSUE THREAD

**Issue by ge-gao** [carbon-design-system/gatsby-theme-carbon#1066]
## Detailed description

> I'm trying to change head color from black to white, but it does not work with shadowing. In browser
> I can see error message about NavHeader.js. But not sure if it is related.

> Browser: Google Chrome Version 86.0.4240.198 (Official Build) (x86_64)
> Node: v12.19.1

## Steps to reproduce the issue

1. npx gatsby new my-carbon-site https://github.com/carbon-design-system/gatsby-starter-carbon-theme 
2. cd my-carbon-site
3. create src/gatsby-theme-carbon/components/Header/header.module.scss

```scss
header.header {
    background-color: $carbon--white-0;
    z-index: 10000;
}
```

3. create src/gatsby-theme-carbon/components/PageHeader/PageHeader.module.scss

```scss
.page-header {
    --height: 20rem;
    height: 20rem;
    height: var(--height);
    background-color: $carbon--white-0;
    color: $carbon--black-100;
    width: 100%;
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
    border-bottom: 1px solid $carbon--gray-10;
}
```

3. edit gatsby-config.js to use white theme and header navigation style

```javascript
...
    {
      resolve: 'gatsby-theme-carbon',
      options: {
        navigationStyle: 'header',
        theme: {
          homepage: 'white',
          interior: 'g10',
        },
      },
    },
...
```

3. yarn dev
4. go to http://localhost:8000

**Expected result**:
1. theme is white
2. page header changes to white background and black text
3. head changes to white background and black text

**Actual result**:
1. theme is white
2. page header changes to white background and black text
3. **_head background is still black and color is white_**

## Additional information

In browser console I can see:

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
> Check the render method of `HeaderNavigation`.
> ... ...

> Warning: React does not recognize the `isActive` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isactive` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

> Warning: Failed prop type: HeaderMenu requires one of the following props: aria-label, aria-labelledby

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
> Check the render method of `HeaderMenu`.
> ... ...

But not sure if it is related.
