### ISSUE TITLE
GraphQL error: Unknown field 'title' on type '[NavItemsYamlPages]'

### ISSUE THREAD

**Issue by pstinnett** [carbon-design-system/gatsby-theme-carbon#323]
Using `data/nav-items.yaml` to build a side nav:

```
- title: Foundation
  pages:
    - path: /foundation
- title: Narrative
  pages:
    - path: /narrative
- title: Programming
  pages:
    - path: /programming
- title: Architecture
  pages:
    - path: /architecture
- title: Branding
  pages:
    - path: /branding
- title: Experience Scenarios
  pages:
    - path: /experience-scenarios
- title: Case Studies
  pages:
    - path: /case-studies
- title: Resources
  pages:
    - path: /resources
```

When I run `npm run dev` or `gatsby build` I receive a GraphQL error:

```
 ERROR #85907  GRAPHQL
There was an error in your GraphQL query:
- Unknown field 'title' on type '[NavItemsYamlPages]'.
File: node_modules/gatsby-theme-carbon/src/components/LeftNav/LeftNav.js
```

Using gatsby-theme-carbon v1.7.1

**Comment by alisonjoseph** [comment]
Confirmed I'm also seeing this error with this yml file.

can you try
```
- title: Foundation
  pages:
    - path: /foundation
- title: Narrative
  pages:
    - path: /narrative
- title: Programming
  pages:
    - path: /programming
- title: Architecture
  pages:
    - path: /architecture
- title: Branding
  pages:
    - path: /branding
- title: Experience Scenarios
  pages:
    - path: /experience-scenarios
- title: Case Studies
  pages:
    - path: /case-studies
- title: Resources
  pages:
    - title: Resources
      path: /resources
```

as a workaround until we can look into this
