### ISSUE TITLE
Trying to increase the sidebar due to long list of components we own

### ISSUE THREAD

**Issue by helmutgranda** [carbon-design-system/gatsby-theme-carbon#722]
## Summary

We have about 50 components or more, they render nicely but the components sidebar menu has a max height:

```css
.#{$prefix}--side-nav__submenu[aria-expanded='true']
+ .#{$prefix}--side-nav__menu[role='menu'] {
max-height: rem(1500px);
visibility: inherit;
background: red;
}
```

I tried to Shadow this file by duplicating it and updating the max-height, say to 2500

`src/carbon-componets/scss/components/ui-shell/_side_nav.scss`

```css
.#{$prefix}--side-nav__submenu[aria-expanded='true']
+ .#{$prefix}--side-nav__menu[role='menu'] {
max-height: rem(2500px);
visibility: inherit;
background: red;
}
```

However, carbon wont let me shadow the file, is there anything specific that I may be missing?

I have tried to overwrite only the section above and also copy the whole file and bring it over.

## Relevant information

File in question:
`src/carbon-componets/scss/components/ui-shell/_side_nav.scss` brought from `node_modules/carbon-components/scss/components/ui-shell/_side_nav.scss`

Path: https://github.com/carbon-design-system/carbon/blob/b8c1e1c57d44b1e4320f60119bf016c83fbc13aa/packages/components/src/components/ui-shell/_side-nav.scss#L444
